### ISSUE TITLE
Termimuutoksia

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#28]
Termimuutokset, joista on ollut meillä puhetta, pitää todellakin tehdä mahdollisista negatiivisista "sivuvaikutuksista" huolimatta. 1. Aktiiviset prosessit -> Käynnissä nyt  (vastaavasti "tulossa" ja "menneet") etusivulla sekä prosessivälilehdellä.  2. Hyväksytty/Hylätty --> Mahdolinen/Ei Mahdollinen.  3.  "Aktiiviset ryhmät otsikko kokonaan pois.

**Comment by katjahenttonen** [comment]
Puhuttiin Helin kanssa, että "aktiiviset ryhmät" etusivulla voisi olla "osallistumisen tueksi".  Ei tarvitse muokata muita kuin etusivun ja prosessivälilehden isoja otsikkoja.

**Comment by ahukkanen** [comment]
Hyväksytty/hylätty -muutos vaikuttaa seuraaviin termeihin, joille tarvittaisiin myös käännökset:

- Hyväksytty
- Hylätty
- Ehdotus hyväksytty
- Ehdotus hylättiin
- Ehdotus "%{resource_title}" on hyväksytty. Voit lukea vastauksen tällä sivulla:
- Seuraamasi ehdotus on hyväksytty
- Ehdotus <a href="%{resource_path}">%{resource_title}</a> on hyväksytty.
- Ehdotus "%{resource_title}" on hylätty. Voit lukea vastauksen tällä sivulla:
- Seuraamasi ehdotus on hylätty
- Ehdotus <a href="%{resource_path}">%{resource_title}</a> on hylätty.
- Tämä käyttäjä on saanut %{score} ehdotusta hyväksytyksi.
- Olet saanut %{score} ehdotusta hyväksyksi.
- Käyttäjät saavat tämän tunnuksen saamalla ehdotuksensa hyväksytyksi.
- Tämä käyttäjä ei ole saanut vielä ehdotuksia hyväksytyksi.
- Sinulla ei ole vielä hyväksyttyjä ehdotuksia.
- Tämä ehdotus on hyväksytty, koska:
- Tämä ehdotus on hylätty, koska:

Laitan tähän vielä ylös nuo käännösavaimet:

```
  activemodel:
    models:
      decidim/proposals/accepted_proposal_event: Ehdotus hyväksytty
      decidim/proposals/rejected_proposal_event: Ehdotus hylättiin
  decidim:
    events:
      proposals:
        proposal_accepted:
          email_intro: 'Ehdotus "%{resource_title}" on hyväksytty. Voit lukea vastauksen tällä sivulla:'
          email_subject: Seuraamasi ehdotus on hyväksytty
          notification_title: Ehdotus <a href="%{resource_path}">%{resource_title}</a> on hyväksytty.
        proposal_rejected:
          email_intro: 'Ehdotus "%{resource_title}" on hylätty. Voit lukea vastauksen tällä sivulla:'
          email_subject: Seuraamasi ehdotus on hylätty
          notification_title: Ehdotus <a href="%{resource_path}">%{resource_title}</a> on hylätty.
    gamification:
      badges:
        accepted_proposals:
          description_another: Tämä käyttäjä on saanut %{score} ehdotusta hyväksytyksi.
          description_own: Olet saanut %{score} ehdotusta hyväksyksi.
          explanation: Käyttäjät saavat tämän tunnuksen saamalla ehdotuksensa hyväksytyksi.
          unearned_another: Tämä käyttäjä ei ole saanut vielä ehdotuksia hyväksytyksi.
          unearned_own: Sinulla ei ole vielä hyväksyttyjä ehdotuksia.
    proposals:
      answers:
        accepted: Hyväksytty
        rejected: Hylätty
      proposals:
        filters:
          accepted: Hyväksytty
          rejected: Hylätty
        show:
          proposal_accepted_reason: 'Tämä ehdotus on hyväksytty, koska:'
          proposal_rejected_reason: 'Tämä ehdotus on hylätty, koska:'
```
